---
  - name: Copy the su file to -> /tmp
    copy: src=su.sh dest=/tmp mode=0755 force
    su: no

  - name: Download the functions template file -> /opt/casfw
    template: src=proxy-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force

  - name: Check if proxy-bundle requires a new installation
    action: command bash {{ casfw_home }}/proxy-functions.sh checkProxyInstallation
    register: checkInstallation

  - debug: msg="Skipping proxy-bundle installation on {{ inventory_hostname }}"
    when: checkInstallation.stdout == "Installed"

  - name: Final cleanup
    action: command bash {{ casfw_home }}/proxy-functions.sh finalCleanup
    when: checkInstallation.stdout == "Installed"

  - name: Complete the deployment
    include: deploy-proxy-bundle.yml
    when: checkInstallation.stdout != "Installed"

  - name: Remove the su file from /tmp/
    shell: cd /tmp/; find -maxdepth 1 -type f -name "su.sh" | xargs rm
    su: no